<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUnitMeasureTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('unit_measure', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 4);
            $table->string('description')->nullable();
            $table->timestamps();
        });
    DB::table('unit_measure')->insert([
        ['code' => '04','description' => 'Pequeño spray'],
        ['code' => '05','description' => 'Elevar'],
        ['code' => '08','description' => 'mucho calor'],
        ['code' => '10','description' => 'Grupo'],
        ['code' => '11','description' => 'Atuendo'],
        ['code' => '13','description' => 'Racionar'],
        ['code' => '14','description' => 'Disparo'],
        ['code' => '15','description' => 'Palo'],
        ['code' => '16','description' => 'Bidón de ciento quince kg'],
        ['code' => '17','description' => 'Tambor de cien libras'],
        ['code' => '18','description' => 'Tambor de cincuenta y cinco galones (EE. UU.)'],
        ['code' => '19','description' => 'Bamión cisterna'],
        ['code' => '20','description' => 'Contenedor de veinte pies'],
        ['code' => '21','description' => 'Contenedor de cuarenta pies'],
        ['code' => '22','description' => 'Decilitro por gramo'],
        ['code' => '23','description' => 'Gramo por centímetro cúbico'],
        ['code' => '24','description' => 'Libra teórica'],
        ['code' => '25','description' => 'Gramo por centímetro cuadrado'],
        ['code' => '26','description' => 'Tonelada real'],
        ['code' => '27','description' => 'Tonelada teórica'],
        ['code' => '28','description' => 'kilogramo por metro cuadrado'],
        ['code' => '57','description' => 'Malla'],
        ['code' => '58','description' => 'Kilogramo neto'],
        ['code' => '59','description' => 'Parte por millón'],
        ['code' => '60','description' => 'Porcentaje de peso'],
        ['code' => '61','description' => 'Partes por mil millones (EE. UU.)'],
        ['code' => '62','description' => 'Por ciento por 1000 horas'],
        ['code' => '63','description' => 'Tasa de fallas en el tiempo'],
        ['code' => '64','description' => 'Libras por pulgada cuadrada, calibre'],
        ['code' => '66','description' => 'Oersted'],
        ['code' => '69','description' => 'Prueba escala específica'],
        ['code' => '71','description' => 'Voltios amperios por libra'],
        ['code' => '72','description' => 'Vatio por libra'],
        ['code' => '73','description' => 'Amperios tum por centímetro'],
        ['code' => '74','description' => 'Milipascal'],
        ['code' => '76','description' => 'Gauss'],
        ['code' => '77','description' => 'Mili-pulgada'],
        ['code' => '78','description' => 'Kilogauss'],
        ['code' => '80','description' => 'Libras por pulgada cuadrada absoluta'],
        ['code' => '81','description' => 'Henry'],
        ['code' => '84','description' => 'Kilo libra por pulgada cuadrada'],
        ['code' => '85','description' => 'Pie libra fuerza'],
        ['code' => '87','description' => 'Libras por pie cúbico'],
        ['code' => '89','description' => 'Equilibrio'],
        ['code' => '90','description' => 'Segundo universal Saybold'],
        ['code' => '91','description' => 'Stokes'],
        ['code' => '92','description' => 'Caloría por centímetro cúbico'],
        ['code' => '93','description' => 'Caloría por gramo'],
        ['code' => '94','description' => 'Unidad de rizo'],
        ['code' => '95','description' => 'Vagón tanque de veinte mil galones (EE. UU.)'],
        ['code' => '96','description' => 'Vagón cisterna de diez mil galones (EE. UU.)'],
        ['code' => '97','description' => 'Tambor de diez kg'],
        ['code' => '98','description' => 'Tambor de quince kg'],
        ['code' => '1A','description' => 'Milla de coche'],
        ['code' => '1B','description' => 'Conteo de autos'],
        ['code' => '1C','description' => 'Recuento de locomotoras'],
        ['code' => '1D','description' => 'Recuento de furgónes de cola'],
        ['code' => '1E','description' => 'Coche vacío'],
        ['code' => '1F','description' => 'Milla de tren'],
        ['code' => '1G','description' => 'Uso de combustible galón (EE. UU.)'],
        ['code' => '1H','description' => 'Milla de furgón de cola'],
        ['code' => '1I','description' => 'Tasa fija'],
        ['code' => '1J','description' => 'Tonelada milla'],
        ['code' => '1K','description' => 'Milla de locomotora'],
        ['code' => '4W','description' => 'Tonelada (EE. UU.) por hora'],
        ['code' => '4X','description' => 'Kilolitro por hora'],
        ['code' => '5A','description' => 'Barril por minuto'],
        ['code' => '5B','description' => 'Lote'],
        ['code' => '5C','description' => 'Galones (EE. UU.) Por mil'],
        ['code' => '5E','description' => 'MMSCF / día'],
        ['code' => '5F','description' => 'Libras por mil'],
        ['code' => '5G','description' => 'Bomba'],
        ['code' => '5H','description' => 'Etapa'],
        ['code' => '5I','description' => 'Pie cúbico estándar'],
        ['code' => '5J','description' => 'Potencia de caballo hidráulica'],
        ['code' => '5K','description' => 'Recuento por minuto'],
        ['code' => '5P','description' => 'Nivel sísmico'],
        ['code' => '5Q','description' => 'Línea sísmica'],
        ['code' => 'A1','description' => '15 C de calorías'],
        ['code' => 'A10','description' => 'Amperios metro cuadrado por joule segundo'],
        ['code' => 'A11','description' => 'Ã ¥ ngstrÃ¶m'],
        ['code' => 'A12','description' => 'Unidad astronómica'],
        ['code' => 'A13','description' => 'Attojoule'],
        ['code' => 'A14','description' => 'Granero'],
        ['code' => 'A15','description' => 'Granero por electronvoltio'],
        ['code' => 'A16','description' => 'Granero por electronvoltio estereorradián,'],
        ['code' => 'A17','description' => 'Granero por esterdian'],
        ['code' => 'A18','description' => 'Becquerel por kilogramo'],
        ['code' => 'A19','description' => 'Becquerel por metro cúbico'],
        ['code' => 'A2','description' => 'Amperios por centímetro'],
        ['code' => 'A20','description' => 'Unidad térmica británica por segundo cuadrado'],
        ['code' => 'A21','description' => 'Unidad térmica británica por libra grado'],
        ['code' => 'A22','description' => 'Unidad térmica británica por segundo pie'],
        ['code' => 'A23','description' => 'Unidad térmica británica por hora pie cuadrado'],
        ['code' => 'A24','description' => 'Candelas por metro cuadrado'],
        ['code' => 'A25','description' => 'Vapeur cheval'],
        ['code' => 'A26','description' => 'Medidor de culombio'],
        ['code' => 'A27','description' => 'Metro de culombio al cuadrado por voltio'],
        ['code' => 'A28','description' => 'Culombios por centímetro cúbico'],
        ['code' => 'A29','description' => 'Culombio por metro cúbico'],
        ['code' => 'A3','description' => 'Amperio por milímetro'],
        ['code' => 'A30','description' => 'Culombio por milímetro cúbico'],
        ['code' => 'A31','description' => 'Culombio por kilogramo segundo'],
        ['code' => 'A74','description' => 'Pie libra fuerza por segundo'],
        ['code' => 'A75','description' => 'Carga tonelada'],
        ['code' => 'A76','description' => 'Galón'],
        ['code' => 'A77','description' => 'Unidad de desplazamiento CGS gaussiana'],
        ['code' => 'A78','description' => 'Unidad CGS gaussiana de corriente eléctrica'],
        ['code' => 'A79','description' => 'Unidad de carga eléctrica gaussiana CGS'],
        ['code' => 'A8','description' => 'Amperio segundo'],
        ['code' => 'A80','description' => 'Unidad de campo eléctrico gaussiano CGS'],
        ['code' => 'A81','description' => 'Unidad de polarización eléctrica gaussiana CGS'],
        ['code' => 'A82','description' => 'Unidad de potencial eléctrico gaussiana CGS'],
        ['code' => 'A83','description' => 'Unidad de magnetización gaussiana CGS'],
        ['code' => 'A84','description' => 'Gigaculombio por metro cúbico'],
        ['code' => 'A85','description' => 'Gigaelectronvoltio'],
        ['code' => 'A86','description' => 'Gigahercio'],
        ['code' => 'A87','description' => 'Gigaohmio'],
        ['code' => 'A88','description' => 'Medidor de gigaohmios'],
        ['code' => 'A89','description' => 'Gigapascal'],
        ['code' => 'A9','description' => 'Índice'],
        ['code' => 'A90','description' => 'Gigavatio'],
        ['code' => 'A91','description' => 'Gon'],
        ['code' => 'A93','description' => 'Gramo por metro cúbico'],
        ['code' => 'A94','description' => 'Gramo por mol'],
        ['code' => 'A95','description' => 'Gris'],
        ['code' => 'A96','description' => 'Gris por segundo'],
        ['code' => 'A97','description' => 'Hectopascal'],
        ['code' => 'A98','description' => 'Henry por metro'],
        ['code' => 'AA','description' => 'Pelota'],
        ['code' => 'AB','description' => 'paquete a granel'],
        ['code' => 'ACR','description' => 'Acre'],
        ['code' => 'AD','description' => 'Byte'],
        ['code' => 'AE','description' => 'Amperio por metro'],
        ['code' => 'AH','description' => 'Minuto adicional'],
        ['code' => 'AI','description' => 'Minuto promedio por llamada'],
        ['code' => 'AJ','description' => 'Cop'],
        ['code' => 'AK','description' => 'Braza'],
        ['code' => 'AL','description' => 'Línea de acceso'],
        ['code' => 'AM','description' => 'Ampolla'],
        ['code' => 'AMH','description' => 'Amperio hora'],
        ['code' => 'AMP','description' => 'Amperio'],
        ['code' => 'ANN','description' => 'Año'],
        ['code' => 'AP','description' => 'Libra de aluminio solamente'],
        ['code' => 'APZ','description' => 'Onza troy o onza de boticario'],
        ['code' => 'B40','description' => 'Kilogramo-fuerza por metro cuadrado'],
        ['code' => 'B41','description' => 'Kilojoule por kelvin'],
        ['code' => 'B42','description' => 'Kilojoule por kilogramo'],
        ['code' => 'B43','description' => 'Kilojoule por kilogramo kelvin'],
        ['code' => 'B44','description' => 'Kilojoule por mol'],
        ['code' => 'B45','description' => 'Kilomole'],
        ['code' => 'B46','description' => 'Kilomole por metro cúbico'],
        ['code' => 'B47','description' => 'Kilonewton'],
        ['code' => 'B48','description' => 'Kilonewton metro'],
        ['code' => 'B49','description' => 'Kiloohmios'],
        ['code' => 'B5','description' => 'Palanquilla'],
        ['code' => 'B50','description' => 'Medidor de kiloohmios'],
        ['code' => 'B51','description' => 'Kilopond'],
        ['code' => 'B52','description' => 'Kilosegundo'],
        ['code' => 'B53','description' => 'Kilosiemens'],
        ['code' => 'B54','description' => 'Kilosiemens por metro'],
        ['code' => 'B55','description' => 'Kilovoltio por metro'],
        ['code' => 'B56','description' => 'Kiloweber por metro'],
        ['code' => 'B57','description' => 'Año luz'],
        ['code' => 'B58','description' => 'Litro por mol'],
        ['code' => 'B59','description' => 'Hora de lumen'],
        ['code' => 'B6','description' => 'Bollo'],
        ['code' => 'B60','description' => 'Lumen por metro cuadrado'],
        ['code' => 'B61','description' => 'Lumen por vatio'],
        ['code' => 'B62','description' => 'Lumen segundo'],
        ['code' => 'B63','description' => 'Hora lux'],
        ['code' => 'B64','description' => 'Lux segundo'],
        ['code' => 'B65','description' => 'Maxwell'],
        ['code' => 'B66','description' => 'Megaamperio por metro cuadrado'],
        ['code' => 'B67','description' => 'Megabecquerel por kilogramo'],
        ['code' => 'B69','description' => 'Megaculombio por metro cúbico'],
        ['code' => 'B7','description' => 'Ciclo'],
        ['code' => 'B70','description' => 'Megaculombio por metro cuadrado'],
        ['code' => 'B71','description' => 'Megaelectronvoltio'],
        ['code' => 'B72','description' => 'Megagramo por metro cúbico'],
        ['code' => 'B73','description' => 'Meganewton'],
        ['code' => 'B74','description' => 'Medidor de meganewton'],
        ['code' => 'B75','description' => 'Megaohmios'],
        ['code' => 'B76','description' => 'Medidor de megaohmios'],
        ['code' => 'B77','description' => 'Megasiemens por metro'],
        ['code' => 'B78','description' => 'Megavoltio'],
        ['code' => 'B79','description' => 'Megavoltio por metro'],
        ['code' => 'B8','description' => 'Joule por metro cúbico'],
        ['code' => 'BX','description' => 'Caja'],
        ['code' => 'BZ','description' => 'Millones de BTU'],
        ['code' => 'C0','description' => 'Llamada'],
        ['code' => 'C1','description' => 'Libra de producto compuesto (peso total)'],
        ['code' => 'C10','description' => 'Millifarad'],
        ['code' => 'C11','description' => 'Milligal'],
        ['code' => 'C12','description' => 'Miligramo por metro'],
        ['code' => 'C13','description' => 'Milligray'],
        ['code' => 'C14','description' => 'Millihenry'],
        ['code' => 'C15','description' => 'Millijoule'],
        ['code' => 'C16','description' => 'Milímetro por segundo'],
        ['code' => 'C17','description' => 'Milímetro cuadrado por segundo'],
        ['code' => 'C18','description' => 'Millimole'],
        ['code' => 'C19','description' => 'Mole por kilogramo'],
        ['code' => 'C2','description' => 'Carset'],
        ['code' => 'C20','description' => 'Millinewton'],
        ['code' => 'C22','description' => 'Millinewton por metro'],
        ['code' => 'C23','description' => 'Medidor de miliohmios'],
        ['code' => 'C24','description' => 'Segundo milipascal'],
        ['code' => 'C25','description' => 'Milliradian'],
        ['code' => 'C26','description' => 'Milisegundo'],
        ['code' => 'C27','description' => 'Millisiemens'],
        ['code' => 'C28','description' => 'Millisievert'],
        ['code' => 'C29','description' => 'Millitesla'],
        ['code' => 'C3','description' => 'Microvoltio por metro'],
        ['code' => 'C30','description' => 'Milivoltios por metro'],
        ['code' => 'C31','description' => 'Milivatios'],
        ['code' => 'C32','description' => 'Milivatios por metro cuadrado'],
        ['code' => 'C33','description' => 'Milliweber'],
        ['code' => 'C34','description' => 'Topo'],
        ['code' => 'C35','description' => 'Mol por decímetro cúbico'],
        ['code' => 'C36','description' => 'Mol por metro cúbico'],
        ['code' => 'C38','description' => 'Mole por litro'],
        ['code' => 'C39','description' => 'Nanoamperio'],
        ['code' => 'C4','description' => 'Partido de carga'],
        ['code' => 'C40','description' => 'Nanocoulomb'],
        ['code' => 'C41','description' => 'Nanofaradio'],
        ['code' => 'C42','description' => 'Nanofaradios por metro'],
        ['code' => 'C43','description' => 'Nanohenry'],
        ['code' => 'C44','description' => 'Nanohenry por metro'],
        ['code' => 'C45','description' => 'Nanómetro'],
        ['code' => 'C46','description' => 'Medidor de nanoohmios'],
        ['code' => 'C47','description' => 'Nanosegundo'],
        ['code' => 'C89','description' => 'Henry recíproco'],
        ['code' => 'C9','description' => 'Grupo de bobinas'],
        ['code' => 'C90','description' => 'Joule recíproco por metro cúbico'],
        ['code' => 'C91','description' => 'Kelvin recíproco o kelvin al poder'],
        ['code' => 'C92','description' => 'Metro recíproco'],
        ['code' => 'C93','description' => 'Metro cuadrado recíproco'],
        ['code' => 'C94','description' => 'Minuto recíproco'],
        ['code' => 'C95','description' => 'Mole recíproco'],
        ['code' => 'C96','description' => 'Pascal recíproco o pascal al poder'],
        ['code' => 'C97','description' => 'Segundo recíproco'],
        ['code' => 'C98','description' => 'Segundo recíproco por metro cúbico'],
        ['code' => 'C99','description' => 'Segundo recíproco por metro cuadrado'],
        ['code' => 'CA','description' => 'Poder'],
        ['code' => 'CCT','description' => 'Capacidad de carga en toneladas métricas'],
        ['code' => 'CDL','description' => 'Candela'],
        ['code' => 'CEL','description' => 'Grado Celsius'],
        ['code' => 'CEN','description' => 'Centenar'],
        ['code' => 'CG','description' => 'Tarjeta'],
        ['code' => 'CGM','description' => 'Centigramo'],
        ['code' => 'CH','description' => 'Envase'],
        ['code' => 'CJ','description' => 'Cono'],
        ['code' => 'CK','description' => 'Conector'],
        ['code' => 'CKG','description' => 'Culombio por kilogramo'],
        ['code' => 'CL','description' => 'Bobina'],
        ['code' => 'CLF','description' => 'Cien se van'],
        ['code' => 'CLT','description' => 'Centilitro'],
        ['code' => 'CMK','description' => 'Centimetro cuadrado'],
        ['code' => 'CMQ','description' => 'Centímetro cúbico'],
        ['code' => 'CMT','description' => 'Centímetro'],
        ['code' => 'CNP','description' => 'Paquete de cien'],
        ['code' => 'CNT','description' => 'Cental (Reino Unido)'],
        ['code' => 'CO','description' => 'Garrafón'],
        ['code' => 'COU','description' => 'Culombio'],
        ['code' => 'CQ','description' => 'Cartucho'],
        ['code' => 'CR','description' => 'Caja'],
        ['code' => 'CS','description' => 'Caso'],
        ['code' => 'CT','description' => 'Caja de cartón'],
        ['code' => 'CTM','description' => 'Quilate métrico'],
        ['code' => 'CU','description' => 'Taza'],
        ['code' => 'CUR','description' => 'Curie'],
        ['code' => 'CV','description' => 'Cubrir'],
        ['code' => 'D45','description' => 'Voltios al cuadrado por kelvin al cuadrado'],
        ['code' => 'D46','description' => 'Voltios - amperios'],
        ['code' => 'D47','description' => 'Voltio por centímetro'],
        ['code' => 'D48','description' => 'Voltios por kelvin'],
        ['code' => 'D49','description' => 'Milivoltios por kelvin'],
        ['code' => 'D5','description' => 'Kilogramo por centímetro cuadrado'],
        ['code' => 'D50','description' => 'Voltios por metro'],
        ['code' => 'D51','description' => 'Voltios por milímetro'],
        ['code' => 'D52','description' => 'Vatio por kelvin'],
        ['code' => 'D53','description' => 'Vatio por metro kelvin'],
        ['code' => 'D54','description' => 'Vatio por metro cuadrado'],
        ['code' => 'D55','description' => 'Vatio por metro cuadrado kelvin'],
        ['code' => 'D56','description' => 'Vatio por metro cuadrado kelvin al'],
        ['code' => 'D57','description' => 'Vatio por estereorradián'],
        ['code' => 'D58','description' => 'Vatios por metro cuadrado estereorradián'],
        ['code' => 'D59','description' => 'Weber por metro'],
        ['code' => 'D6','description' => 'RÃ¶ntgen por segundo'],
        ['code' => 'D60','description' => 'Weber por milímetro'],
        ['code' => 'D61','description' => 'Minuto'],
        ['code' => 'D62','description' => 'Segundo'],
        ['code' => 'D63','description' => 'Libro'],
        ['code' => 'D64','description' => 'Bloque'],
        ['code' => 'D65','description' => 'Ronda'],
        ['code' => 'D66','description' => 'Casete'],
        ['code' => 'D67','description' => 'Dólar por hora'],
        ['code' => 'D69','description' => 'Pulgada a la cuarta potencia'],
        ['code' => 'D7','description' => 'Sandwich'],
        ['code' => 'D70','description' => 'Caloría de tabla internacional (IT)'],
        ['code' => 'D71','description' => 'Calorías de Tabla Internacional (IT) por segundo'],
        ['code' => 'D72','description' => 'Calorías de Tabla Internacional (IT) por segundo'],
        ['code' => 'D73','description' => 'Joule metro cuadrado'],
        ['code' => 'D74','description' => 'Kilogramo por mol'],
        ['code' => 'D75','description' => 'Caloría de Tabla Internacional (IT) por gramo'],
        ['code' => 'D76','description' => 'Caloría de Tabla Internacional (IT) por gramo'],
        ['code' => 'D77','description' => 'Megaculombio'],
        ['code' => 'D79','description' => 'Beam'],
        ['code' => 'D8','description' => 'Puntuación draize'],
        ['code' => 'D80','description' => 'Microwatt'],
        ['code' => 'D81','description' => 'Microtesla'],
        ['code' => 'DS','description' => 'Visualización'],
        ['code' => 'DT','description' => 'Tonelada seca'],
        ['code' => 'DTN','description' => 'Decitonne'],
        ['code' => 'DU','description' => 'Dina'],
        ['code' => 'DWT','description' => 'Pennyweight'],
        ['code' => 'DX','description' => 'Dina por centímetro'],
        ['code' => 'DY','description' => 'Libro de directorio'],
        ['code' => 'DZN','description' => 'Docena'],
        ['code' => 'DZP','description' => 'Paquete de docena'],
        ['code' => 'E2','description' => 'Cinturón'],
        ['code' => 'E3','description' => 'Remolque'],
        ['code' => 'E4','description' => 'Kilogramo bruto'],
        ['code' => 'E5','description' => 'Tonelada larga métrica'],
        ['code' => 'EA','description' => 'Cada'],
        ['code' => 'EB','description' => 'Buzón de correo electrónico'],
        ['code' => 'EC','description' => 'Cada uno por mes'],
        ['code' => 'EP','description' => 'Paquete de once'],
        ['code' => 'EQ','description' => 'Galón equivalente'],
        ['code' => 'EV','description' => 'Sobre'],
        ['code' => 'F1','description' => 'Mil pies cúbicos por día'],
        ['code' => 'F9','description' => 'Fibra por centímetro cúbico de aire'],
        ['code' => 'FAH','description' => 'Grado Fahrenheit'],
        ['code' => 'FAR','description' => 'Faradio'],
        ['code' => 'FB','description' => 'Campo'],
        ['code' => 'FC','description' => 'Mil pies cúbicos'],
        ['code' => 'FD','description' => 'Millón de partículas por pie cúbico'],
        ['code' => 'FE','description' => 'Pie de pista'],
        ['code' => 'FF','description' => 'Cien metros cúbicos'],
        ['code' => 'FG','description' => 'Parche transdérmico'],
        ['code' => 'FH','description' => 'Micromol'],
        ['code' => 'FL','description' => 'Tonelada de escamas'],
        ['code' => 'FM','description' => 'Millones de pies cúbicos'],
        ['code' => 'FOT','description' => 'Pie'],
        ['code' => 'FP','description' => 'Libra por pie cuadrado'],
        ['code' => 'FR','description' => 'Pie por minuto'],
        ['code' => 'FS','description' => 'Pie por segundo'],
        ['code' => 'FTK','description' => 'Pie cuadrado'],
        ['code' => 'FTQ','description' => 'Pie cubico'],
        ['code' => 'G2','description' => 'Galones estadounidenses por minuto'],
        ['code' => 'G3','description' => 'Galón imperial por minuto'],
        ['code' => 'G7','description' => 'Hoja de microficha'],
        ['code' => 'GB','description' => 'Galón (EE. UU.) por día'],
        ['code' => 'GBQ','description' => 'Gigabecquerel'],
        ['code' => 'HI','description' => 'Cien hojas'],
        ['code' => 'HIU','description' => 'Cien unidad internacional'],
        ['code' => 'HJ','description' => 'Caballos de fuerza métricos'],
        ['code' => 'HK','description' => 'Cien kilogramos'],
        ['code' => 'HL','description' => 'Cien pies (lineal)'],
        ['code' => 'HLT','description' => 'Hectolitro'],
        ['code' => 'HM','description' => 'Milla por hora'],
        ['code' => 'HMQ','description' => 'Millones de metros cúbicos'],
        ['code' => 'HMT','description' => 'Hectómetro'],
        ['code' => 'HN','description' => 'Milímetro convencional de mercurio'],
        ['code' => 'HO','description' => 'Cien onzas troy'],
        ['code' => 'HP','description' => 'Milímetro convencional de agua'],
        ['code' => 'HPA','description' => 'Hectolitro de alcohol puro'],
        ['code' => 'HS','description' => 'Cien pies cuadrados'],
        ['code' => 'HT','description' => 'Media hora'],
        ['code' => 'HTZ','description' => 'Hertz'],
        ['code' => 'HUR','description' => 'Hora'],
        ['code' => 'HY','description' => 'Cien yardas'],
        ['code' => 'IA','description' => 'Pulgada libra (libra pulgada)'],
        ['code' => 'IC','description' => 'Contar por pulgada'],
        ['code' => 'IE','description' => 'Persona'],
        ['code' => 'IF','description' => 'Pulgadas de agua'],
        ['code' => 'II','description' => 'Pulgada de columna'],
        ['code' => 'IL','description' => 'Pulgada por minuto'],
        ['code' => 'IM','description' => 'Impresión'],
        ['code' => 'INH','description' => 'Pulgada'],
        ['code' => 'INK','description' => 'Pulgada cuadrada'],
        ['code' => 'INQ','description' => 'Pulgada en cubos'],
        ['code' => 'IP','description' => 'Póliza de seguros'],
        ['code' => 'IT','description' => 'Contar por centímetro'],
        ['code' => 'IU','description' => 'Pulgada por segundo (velocidad lineal)'],
        ['code' => 'IV','description' => 'Pulgada por segundo al cuadrado (aceleración)'],
        ['code' => 'J2','description' => 'Joule por kilogramo'],
        ['code' => 'JB','description' => 'Jumbo'],
        ['code' => 'JE','description' => 'Joule por Kelvin'],
        ['code' => 'JG','description' => 'Jarra'],
        ['code' => 'JK','description' => 'Megajoule por kilogramo'],
        ['code' => 'JM','description' => 'Megajoule por metro cúbico'],
        ['code' => 'JO','description' => 'Articulación'],
        ['code' => 'JOU','description' => 'Joule'],
        ['code' => 'JR','description' => 'Frasco'],
        ['code' => 'K1','description' => 'Demanda de kilovatios'],
        ['code' => 'K2','description' => 'Demanda reactiva de kilovoltios amperios'],
        ['code' => 'KW','description' => 'Kilogramos por milímetro'],
        ['code' => 'KWH','description' => 'Kilovatio hora'],
        ['code' => 'KWT','description' => 'Kilovatio'],
        ['code' => 'KX','description' => 'Mililitro por kilogramo'],
        ['code' => 'L2','description' => 'Litro por minuto'],
        ['code' => 'LA','description' => 'Libra por pulgada cúbica'],
        ['code' => 'LBR','description' => 'Libra'],
        ['code' => 'LBT','description' => 'Libra troy (EE. UU.)'],
        ['code' => 'LC','description' => 'Centímetro lineal'],
        ['code' => 'LD','description' => 'Litro por día'],
        ['code' => 'LE','description' => 'Lite'],
        ['code' => 'LEF','description' => 'Hoja'],
        ['code' => 'LF','description' => 'Pie lineal'],
        ['code' => 'LH','description' => 'Hora laboral'],
        ['code' => 'LI','description' => 'Pulgada lineal'],
        ['code' => 'LJ','description' => 'Spray grande'],
        ['code' => 'LK','description' => 'Enlace'],
        ['code' => 'LM','description' => 'Metro lineal'],
        ['code' => 'LN','description' => 'Largo'],
        ['code' => 'LO','description' => 'Lote'],
        ['code' => 'LP','description' => 'Libra líquida'],
        ['code' => 'LPA','description' => 'Litro de alcohol puro'],
        ['code' => 'LR','description' => 'Capa'],
        ['code' => 'LS','description' => 'Suma global'],
        ['code' => 'LTN','description' => 'Ton (Reino Unido) o longton (EE. UU.)'],
        ['code' => 'LTR','description' => 'Litro'],
        ['code' => 'LUM','description' => 'Lumen'],
        ['code' => 'LUX','description' => 'Lux'],
        ['code' => 'LX','description' => 'Yarda lineal por libra'],
        ['code' => 'LY','description' => 'Yarda lineal'],
        ['code' => 'M0','description' => 'Cinta magnética'],
        ['code' => 'M1','description' => 'Miligramos por litro'],
        ['code' => 'M4','description' => 'Valor monetario'],
        ['code' => 'M5','description' => 'Microcurio'],
        ['code' => 'M7','description' => 'Micro-pulgada'],
        ['code' => 'M9','description' => 'Millones de Btu por 1000 pies cúbicos'],
        ['code' => 'MA','description' => 'Máquina por unidad'],
        ['code' => 'MAL','description' => 'Mega litro'],
        ['code' => 'MAM','description' => 'Megametre'],
        ['code' => 'MAW','description' => 'Megavatio'],
        ['code' => 'MBE','description' => 'Equivalente a mil ladrillos estándar'],
        ['code' => 'MBF','description' => 'Mil pies tablares'],
        ['code' => 'MBR','description' => 'Millibar'],
        ['code' => 'NF','description' => 'Mensaje'],
        ['code' => 'NG','description' => 'Galón neto (nosotros)'],
        ['code' => 'NH','description' => 'Hora del mensaje'],
        ['code' => 'NI','description' => 'Galón imperial neto'],
        ['code' => 'NIU','description' => 'Número de unidades internacionales'],
        ['code' => 'NJ','description' => 'Número de pantallas'],
        ['code' => 'NL','description' => 'Carga'],
        ['code' => 'NMI','description' => 'Milla nautica'],
        ['code' => 'NMP','description' => 'Número de paquetes'],
        ['code' => 'NN','description' => 'Tren'],
        ['code' => 'NPL','description' => 'Número de parcelas'],
        ['code' => 'NPR','description' => 'Número de pares'],
        ['code' => 'NPT','description' => 'Número de partes'],
        ['code' => 'NQ','description' => 'Mho'],
        ['code' => 'NR','description' => 'Micromho'],
        ['code' => 'NRL','description' => 'Número de rollos'],
        ['code' => 'NT','description' => 'Tonelada neta'],
        ['code' => 'NTT','description' => 'Tonelada de registro neto'],
        ['code' => 'UN','description' => 'Newton metro'],
        ['code' => 'NV','description' => 'Vehículo'],
        ['code' => 'NX','description' => 'Parte por mil'],
        ['code' => 'NY','description' => 'Libra por tonelada métrica seca al aire'],
        ['code' => 'OA','description' => 'Panel'],
        ['code' => 'OHM','description' => 'Ohm'],
        ['code' => 'ON','description' => 'Onza por yarda cuadrada'],
        ['code' => 'ONZ','description' => 'Onza'],
        ['code' => 'OP','description' => 'Dos paquetes'],
        ['code' => 'OT','description' => 'Hora extra'],
        ['code' => 'OZ','description' => 'Onza av'],
        ['code' => 'OZA','description' => 'Onza líquida (EE. UU.)'],
        ['code' => 'OZI','description' => 'Onza líquida (Reino Unido)'],
        ['code' => 'P0','description' => 'Página - electrónico'],
        ['code' => 'P1','description' => 'Por ciento'],
        ['code' => 'P2','description' => 'Libra por pie'],
        ['code' => 'P3','description' => 'Paquete de tres'],
        ['code' => 'P4','description' => 'Paquete de cuatro'],
        ['code' => 'P5','description' => 'Paquete de cinco'],
        ['code' => 'P6','description' => 'Paquete de seis'],
        ['code' => 'P7','description' => 'Paquete de siete'],
        ['code' => 'P8','description' => 'Paquete de ocho'],
        ['code' => 'P9','description' => 'Paquete de nueve'],
        ['code' => 'PA','description' => 'Paquete'],
        ['code' => 'PAL','description' => 'Pascal'],
        ['code' => 'RH','description' => 'Horas de funcionamiento o de funcionamiento'],
        ['code' => 'RK','description' => 'Medida métrica del rollo'],
        ['code' => 'RL','description' => 'Carrete'],
        ['code' => 'RM','description' => 'Resma'],
        ['code' => 'RN','description' => 'Resma medida métrica'],
        ['code' => 'RO','description' => 'Rodar'],
        ['code' => 'RP','description' => 'Libra por resma'],
        ['code' => 'RPM','description' => 'Revoluciones por minuto'],
        ['code' => 'RPS','description' => 'Revoluciones por segundo'],
        ['code' => 'RS','description' => 'Reiniciar'],
        ['code' => 'RT','description' => 'Ingresos tonelada milla'],
        ['code' => 'RU','description' => 'Correr'],
        ['code' => 'S3','description' => 'Pie cuadrado por segundo'],
        ['code' => 'S4','description' => 'Metro cuadrado por segundo'],
        ['code' => 'S5','description' => 'Sesenta cuartos de pulgada'],
        ['code' => 'S6','description' => 'Sesión'],
        ['code' => 'S7','description' => 'Unidad de almacenamiento'],
        ['code' => 'S8','description' => 'Unidad publicitaria estándar'],
        ['code' => 'SA','description' => 'Saco'],
        ['code' => 'SAN','description' => 'Medio año (6 meses)'],
        ['code' => 'SCO','description' => 'Puntaje'],
        ['code' => 'SCR','description' => 'Escrúpulo'],
        ['code' => 'SD','description' => 'Libra sólida'],
        ['code' => 'SE','description' => 'Sección'],
        ['code' => 'SEC','description' => 'Segundo'],
        ['code' => 'SET','description' => 'Colocar'],
        ['code' => 'SG','description' => 'Segmento'],
        ['code' => 'SHT','description' => 'Tonelada de envío'],
        ['code' => 'SIE','description' => 'Siemens'],
        ['code' => 'SK','description' => 'Camión cisterna dividido'],
        ['code' => 'SL','description' => 'Hoja de deslizamiento'],
        ['code' => 'SMI','description' => 'Milla (milla terrestre)'],
        ['code' => 'SN','description' => 'Varilla cuadrada'],
        ['code' => 'SO','description' => 'Carrete'],
        ['code' => 'SP','description' => 'Paquete de estantería'],
        ['code' => 'SQ','description' => 'Cuadrado'],
        ['code' => 'SR','description' => 'Banda'],
        ['code' => 'SS','description' => 'medida métrica hoja'],
        ['code' => 'SST','description' => 'Estándar corto (7200 coincidencias)'],
        ['code' => 'ST','description' => 'Hoja'],
        ['code' => 'STI','description' => 'Piedra (Reino Unido)'],
        ['code' => 'STN','description' => 'Tonelada (EE. UU.) o tonelada corta (Reino Unido / EE. UU.)'],
        ['code' => 'SV','description' => 'Patinar'],
        ['code' => 'UE','description' => 'Décima hora'],
        ['code' => 'UF','description' => 'Uso por línea de telecomunicaciones'],
        ['code' => 'UH','description' => 'Diez mil yardas'],
        ['code' => 'UM','description' => 'Millones de unidades'],
        ['code' => 'VA','description' => 'Voltios amperios por kilogramo'],
        ['code' => 'VI','description' => 'Frasco'],
        ['code' => 'VLT','description' => 'Voltio'],
        ['code' => 'VQ','description' => 'A granel'],
        ['code' => 'VS','description' => 'Visita'],
        ['code' => 'W2','description' => 'Kilo mojado'],
        ['code' => 'W4','description' => 'Dos semanas'],
        ['code' => 'WA','description' => 'Vatio por kilogramo'],
        ['code' => 'WB','description' => 'Libra mojada'],
        ['code' => 'WCD','description' => 'Cable'],
        ['code' => 'WE','description' => 'Tonelada húmeda'],
        ['code' => 'WEB','description' => 'Weber'],
        ['code' => 'WEE','description' => 'Semana'],
        ['code' => 'WG','description' => 'Galón de vino'],
        ['code' => 'WH','description' => 'Rueda'],
        ['code' => 'WHR','description' => 'Vatios hora'],
        ['code' => '29','description' => 'Libra por mil pies cuadrados'],
        ['code' => '30','description' => 'Caballos de fuerza por día por tonelada métrica seca al aire'],
        ['code' => '31','description' => 'Peso de captura'],
        ['code' => '32','description' => 'Kilogramo por tonelada métrica seca al aire'],
        ['code' => '33','description' => 'Kilopascal metros cuadrados por gramo'],
        ['code' => '34','description' => 'Kilopascales por milímetro'],
        ['code' => '35','description' => 'Mililitros por centímetro cuadrado segundo'],
        ['code' => '36','description' => 'Pies cúbicos por minuto por pie cuadrado'],
        ['code' => '37','description' => 'Onza por pie cuadrado'],
        ['code' => '38','description' => 'Onzas por pie cuadrado por 0,01 pulgada'],
        ['code' => '40','description' => 'Mililitro por segundo'],
        ['code' => '41','description' => 'Mililitro por minuto'],
        ['code' => '43','description' => 'Súper bolsa a granel'],
        ['code' => '44','description' => 'super saco de quinientos kg'],
        ['code' => '45','description' => 'Super saco de trescientos kg'],
        ['code' => '46','description' => 'Bolsa a granel de cincuenta libras'],
        ['code' => '47','description' => 'Bolsa de cincuenta libras'],
        ['code' => '48','description' => 'Carga de carro a granel'],
        ['code' => '53','description' => 'Kilogramos teóricos'],
        ['code' => '54','description' => 'Tono teórico'],
        ['code' => '56','description' => 'Sitas'],
        ['code' => '1L','description' => 'Recuento total de automóviles'],
        ['code' => '1M','description' => 'Milla total del coche'],
        ['code' => '1X','description' => 'Cuarto de milla'],
        ['code' => '2A','description' => 'Radianes por segundo'],
        ['code' => '2B','description' => 'Radianes por segundo al cuadrado'],
        ['code' => '2C','description' => 'RÃ¶ntgen'],
        ['code' => '2I','description' => 'Unidad térmica británica por hora'],
        ['code' => '2J','description' => 'Centímetro cúbico por segundo'],
        ['code' => '2K','description' => 'Pie cúbico por hora'],
        ['code' => '2L','description' => 'Pie cúbico por minuto'],
        ['code' => '2M','description' => 'Centímetro por segundo'],
        ['code' => '2N','description' => 'Decibel'],
        ['code' => '2P','description' => 'Kilobyte'],
        ['code' => '2Q','description' => 'Kilobecquerel'],
        ['code' => '2R','description' => 'Kilocurie'],
        ['code' => '2U','description' => 'Megagramo'],
        ['code' => '2V','description' => 'Megagramo por hora'],
        ['code' => '2W','description' => 'Compartimiento'],
        ['code' => '2X','description' => 'Metro por minuto'],
        ['code' => '2Y','description' => 'MillirÃ¶ntgen'],
        ['code' => '2Z','description' => 'Milivoltio'],
        ['code' => '3B','description' => 'Megajoule'],
        ['code' => '3C','description' => 'Manmonth'],
        ['code' => '3E','description' => 'Libra por libra de producto'],
        ['code' => '3G','description' => 'Libra por pieza de producto'],
        ['code' => '3H','description' => 'Kilogramo por kilogramo de producto'],
        ['code' => '3I','description' => 'Kilogramo por pieza de producto'],
        ['code' => '4A','description' => 'Bobina'],
        ['code' => '4B','description' => 'Gorra'],
        ['code' => '4C','description' => 'Centistokes'],
        ['code' => '4E','description' => 'Paquete de veinte'],
        ['code' => '4G','description' => 'Microlitros'],
        ['code' => '4H','description' => 'Micrómetro (micrón)'],
        ['code' => '4K','description' => 'Miliamperios'],
        ['code' => '4L','description' => 'Megabyte'],
        ['code' => '4M','description' => 'Miligramo por hora'],
        ['code' => '4N','description' => 'Megabecquerel'],
        ['code' => '4O','description' => 'Microfaradio'],
        ['code' => '4P','description' => 'Newton por metro'],
        ['code' => '4Q','description' => 'Onza de pulgada'],
        ['code' => '4R','description' => 'Pie de onza'],
        ['code' => '4T','description' => 'Picofaradio'],
        ['code' => '4U','description' => 'Libra por hora'],
        ['code' => 'A32','description' => 'Culombio por mol'],
        ['code' => 'A33','description' => 'Culombio por centímetro cuadrado'],
        ['code' => 'A34','description' => 'Culombio por metro cuadrado'],
        ['code' => 'A35','description' => 'Culombio por milímetro cuadrado'],
        ['code' => 'A36','description' => 'Centímetro cúbico por mol'],
        ['code' => 'A37','description' => 'Decímetro cúbico por mol'],
        ['code' => 'A38','description' => 'Metro cúbico por culombio'],
        ['code' => 'A39','description' => 'Metro cúbico por kilogramo'],
        ['code' => 'A4','description' => 'Amperio por centímetro cuadrado'],
        ['code' => 'A40','description' => 'Metro cúbico por mol'],
        ['code' => 'A41','description' => 'Amperio por metro cuadrado'],
        ['code' => 'A42','description' => 'Curie por kilogramo'],
        ['code' => 'A43','description' => 'Tonelaje de peso muerto'],
        ['code' => 'A44','description' => 'Decalitro'],
        ['code' => 'A45','description' => 'Decámetro'],
        ['code' => 'A47','description' => 'Decitex'],
        ['code' => 'A48','description' => 'Grado Rankin'],
        ['code' => 'A49','description' => 'Negacionista'],
        ['code' => 'A5','description' => 'Amperio metro cuadrado'],
        ['code' => 'A50','description' => 'Dyn segundos por centímetro cúbico'],
        ['code' => 'A51','description' => 'Dina segundo por centímetro'],
        ['code' => 'A52','description' => 'Dina segundo por centímetro a la quinta'],
        ['code' => 'A53','description' => 'Electronvoltio'],
        ['code' => 'A54','description' => 'Electronvoltio por metro'],
        ['code' => 'A55','description' => 'Metro cuadrado de electronvoltio'],
        ['code' => 'A56','description' => 'Electronvoltio metro cuadrado por kilogramo'],
        ['code' => 'A57','description' => 'Ergio'],
        ['code' => 'A58','description' => 'Ergio por centímetro'],
        ['code' => 'A6','description' => 'Amperio por metro cuadrado kelvin al cuadrado'],
        ['code' => 'A60','description' => 'Ergio por centímetro cúbico'],
        ['code' => 'A61','description' => 'Ergio por gramo'],
        ['code' => 'A62','description' => 'Ergio por gramo segundo'],
        ['code' => 'A63','description' => 'Ergio por segundo'],
        ['code' => 'A64','description' => 'Ergio por segundo centímetro cuadrado'],
        ['code' => 'A65','description' => 'Ergio por centímetro cuadrado segundo'],
        ['code' => 'A66','description' => 'Ergio centímetro cuadrado'],
        ['code' => 'A67','description' => 'Ergio centímetro cuadrado por gramo'],
        ['code' => 'A68','description' => 'Exajoule'],
        ['code' => 'A69','description' => 'Faradios por metro'],
        ['code' => 'A7','description' => 'Amperio por milímetro cuadrado'],
        ['code' => 'A70','description' => 'Femtojoule'],
        ['code' => 'A71','description' => 'Femtometro'],
        ['code' => 'A73','description' => 'Pies por segundo al cuadrado'],
        ['code' => 'AQ','description' => 'Unidad de factor antihemofílico (AHF)'],
        ['code' => 'AR','description' => 'Supositorio'],
        ['code' => 'ARE','description' => 'Are'],
        ['code' => 'AS','description' => 'Surtido'],
        ['code' => 'ASM','description' => 'Grado alcohólico en masa'],
        ['code' => 'ASU','description' => 'Grado alcohólico volumétrico'],
        ['code' => 'ATM','description' => 'Atmósfera estándar'],
        ['code' => 'ATT','description' => 'Atmósfera técnica'],
        ['code' => 'AV','description' => 'Cápsula'],
        ['code' => 'AW','description' => 'Vial lleno de polvo'],
        ['code' => 'AY','description' => 'Montaje'],
        ['code' => 'AZ','description' => 'Unidad térmica británica por libra'],
        ['code' => 'B0','description' => 'Btu por pie cúbico'],
        ['code' => 'B1','description' => 'Barril (EE. UU.) por día'],
        ['code' => 'B11','description' => 'Joule por kilogramo kelvin'],
        ['code' => 'B12','description' => 'Joule por metro'],
        ['code' => 'B13','description' => 'Joule por metro cuadrado'],
        ['code' => 'B14','description' => 'Joule por metro a la cuarta potencia'],
        ['code' => 'B15','description' => 'Joule por mol'],
        ['code' => 'B16','description' => 'Joule por mol kelvin'],
        ['code' => 'B18','description' => 'Joule segundo'],
        ['code' => 'B2','description' => 'Litera'],
        ['code' => 'B20','description' => 'Joule metro cuadrado por kilogramo'],
        ['code' => 'B21','description' => 'Kelvin por vatio'],
        ['code' => 'B22','description' => 'Kiloamperios'],
        ['code' => 'B23','description' => 'Kiloamperio por metro cuadrado'],
        ['code' => 'B24','description' => 'Kiloamperio por metro'],
        ['code' => 'B25','description' => 'Kilobecquerel por kilogramo'],
        ['code' => 'B26','description' => 'Kilocoulomb'],
        ['code' => 'B27','description' => 'Kilocoulomb por metro cúbico'],
        ['code' => 'B28','description' => 'Kilocoulomb por metro cuadrado'],
        ['code' => 'B29','description' => 'Kiloelectronvoltio'],
        ['code' => 'B3','description' => 'Libra de bateo'],
        ['code' => 'B31','description' => 'Kilogramo metro por segundo'],
        ['code' => 'B32','description' => 'Kilogramo metro cuadrado'],
        ['code' => 'B33','description' => 'Kilogramo metro cuadrado por segundo'],
        ['code' => 'B34','description' => 'Kilogramo por decímetro cúbico'],
        ['code' => 'B35','description' => 'Kilogramo por litro'],
        ['code' => 'B36','description' => 'Caloría termoquímica por gramo'],
        ['code' => 'B37','description' => 'Kilogramo-fuerza'],
        ['code' => 'B38','description' => 'Medidor de kilogramo-fuerza'],
        ['code' => 'B39','description' => 'Metro de kilogramo-fuerza por segundo'],
        ['code' => 'B4','description' => 'Barril, imperial'],
        ['code' => 'B81','description' => 'Recíproco metro cuadrado recíproco'],
        ['code' => 'B83','description' => 'Metro a la cuarta potencia'],
        ['code' => 'B84','description' => 'Microamperios'],
        ['code' => 'B85','description' => 'Microbarra'],
        ['code' => 'B86','description' => 'Microculombio'],
        ['code' => 'B87','description' => 'Microculombio por metro cúbico'],
        ['code' => 'B88','description' => 'Microculombio por metro cuadrado'],
        ['code' => 'B89','description' => 'Microfaradios por metro'],
        ['code' => 'B9','description' => 'Batt'],
        ['code' => 'B90','description' => 'Microhenry'],
        ['code' => 'B91','description' => 'Microhenry por metro'],
        ['code' => 'B92','description' => 'Micronewton'],
        ['code' => 'B93','description' => 'Medidor de micronewton'],
        ['code' => 'B94','description' => 'Microohmios'],
        ['code' => 'B95','description' => 'Medidor de microohmios'],
        ['code' => 'B96','description' => 'Micropascal'],
        ['code' => 'B97','description' => 'Microradian'],
        ['code' => 'B98','description' => 'Microsegundo'],
        ['code' => 'B99','description' => 'Microsiemens'],
        ['code' => 'BAR','description' => 'Bar'],
        ['code' => 'BB','description' => 'Caja base'],
        ['code' => 'BD','description' => 'Tablero'],
        ['code' => 'BE','description' => 'Manojo'],
        ['code' => 'BFT','description' => 'Pie de tabla'],
        ['code' => 'BG','description' => 'Bolsa'],
        ['code' => 'BH','description' => 'Cepillo'],
        ['code' => 'BHP','description' => 'Potencia al freno'],
        ['code' => 'BIL','description' => 'Billón (EE. UU.)'],
        ['code' => 'BJ','description' => 'Balde'],
        ['code' => 'BK','description' => 'Cesta'],
        ['code' => 'BL','description' => 'Bala'],
        ['code' => 'BLD','description' => 'Barril seco (EE. UU.)'],
        ['code' => 'BLL','description' => 'Barril (EE. UU.) (petróleo, etc.)'],
        ['code' => 'BO','description' => 'Botella'],
        ['code' => 'BP','description' => 'Cien pies tablares'],
        ['code' => 'BQL','description' => 'Becquerel'],
        ['code' => 'BR','description' => 'Bar'],
        ['code' => 'BT','description' => 'Tornillo'],
        ['code' => 'BTU','description' => 'Unidad Térmica Británica'],
        ['code' => 'BUA','description' => 'Bushel (EE. UU.)'],
        ['code' => 'BUI','description' => 'Bushel (Reino Unido)'],
        ['code' => 'BW','description' => 'Peso base'],
        ['code' => 'C48','description' => 'Nanotesla'],
        ['code' => 'C49','description' => 'Nanowatt'],
        ['code' => 'C5','description' => 'Costo'],
        ['code' => 'C50','description' => 'Neper'],
        ['code' => 'C51','description' => 'Neper por segundo'],
        ['code' => 'C52','description' => 'Picómetro'],
        ['code' => 'C53','description' => 'Newton metro segundo'],
        ['code' => 'C54','description' => 'Newton metro cuadrado kilogramo cuadrado'],
        ['code' => 'C55','description' => 'Newton por metro cuadrado'],
        ['code' => 'C56','description' => 'Newton por milímetro cuadrado'],
        ['code' => 'C57','description' => 'Newton segundo'],
        ['code' => 'C58','description' => 'Newton segundo por metro'],
        ['code' => 'C59','description' => 'Octava'],
        ['code' => 'C6','description' => 'Celda'],
        ['code' => 'C60','description' => 'Ohmio centímetro'],
        ['code' => 'C61','description' => 'Medidor de ohmios'],
        ['code' => 'C62','description' => 'Uno'],
        ['code' => 'C63','description' => 'Parsec'],
        ['code' => 'C64','description' => 'Pascal por kelvin'],
        ['code' => 'C65','description' => 'Segundo pascal'],
        ['code' => 'C66','description' => 'Segundo pascal por metro cúbico'],
        ['code' => 'C67','description' => 'Segundo pascal por metro'],
        ['code' => 'C68','description' => 'Petajoule'],
        ['code' => 'C69','description' => 'Teléfono'],
        ['code' => 'C7','description' => 'Centipoise'],
        ['code' => 'C70','description' => 'Picoamperio'],
        ['code' => 'C71','description' => 'Picoculombio'],
        ['code' => 'C72','description' => 'Picofaradio por metro'],
        ['code' => 'C73','description' => 'Picohenry'],
        ['code' => 'C75','description' => 'Picowatt'],
        ['code' => 'C76','description' => 'Picowatt por metro cuadrado'],
        ['code' => 'C77','description' => 'Calibre de libra'],
        ['code' => 'C78','description' => 'Libra fuerza'],
        ['code' => 'C8','description' => 'Milicoulomb por kilogramo'],
        ['code' => 'C80','description' => 'Rad'],
        ['code' => 'C81','description' => 'Radián'],
        ['code' => 'C82','description' => 'Radián metro cuadrado por mol'],
        ['code' => 'C83','description' => 'Radián metro cuadrado por kilogramo'],
        ['code' => 'C84','description' => 'Radianes por metro'],
        ['code' => 'C85','description' => 'Recíproco â€ ngstr"m'],
        ['code' => 'C86','description' => 'Metro cúbico recíproco'],
        ['code' => 'C87','description' => 'Metro cúbico recíproco por segundo'],
        ['code' => 'C88','description' => 'Electronvoltio recíproco por metro cúbico'],
        ['code' => 'CWA','description' => 'Cien libras (cwt) / cien peso'],
        ['code' => 'CWI','description' => 'Cien pesos (Reino Unido)'],
        ['code' => 'CY','description' => 'Cilindro'],
        ['code' => 'CZ','description' => 'Combo'],
        ['code' => 'D1','description' => 'Segundo recíproco por estereorradián'],
        ['code' => 'D10','description' => 'Siemens por metro'],
        ['code' => 'D12','description' => 'Siemens metro cuadrado por mol'],
        ['code' => 'D13','description' => 'Sievert'],
        ['code' => 'D14','description' => 'Mil yardas lineales'],
        ['code' => 'D15','description' => 'Sone'],
        ['code' => 'D16','description' => 'Centímetro cuadrado por ergio'],
        ['code' => 'D17','description' => 'Centímetro cuadrado por ergio estereorradián'],
        ['code' => 'D18','description' => 'Metro kelvin'],
        ['code' => 'D19','description' => 'Metro cuadrado kelvin por vatio'],
        ['code' => 'D2','description' => 'Segundo recíproco por metro estereorradián'],
        ['code' => 'D20','description' => 'Metro cuadrado por joule'],
        ['code' => 'D21','description' => 'Metro cuadrado por kilogramo'],
        ['code' => 'D22','description' => 'Metro cuadrado por mol'],
        ['code' => 'D23','description' => 'Pen gram (proteína)'],
        ['code' => 'D24','description' => 'Metro cuadrado por estereorradián'],
        ['code' => 'D25','description' => 'Metro cuadrado por joule estereorradián'],
        ['code' => 'D26','description' => 'Metro cuadrado por voltio segundo'],
        ['code' => 'D27','description' => 'Estereorradián'],
        ['code' => 'D28','description' => 'Sifón'],
        ['code' => 'D29','description' => 'Terahercios'],
        ['code' => 'D30','description' => 'Terajoule'],
        ['code' => 'D31','description' => 'Teravatio'],
        ['code' => 'D32','description' => 'Teravatio hora'],
        ['code' => 'D33','description' => 'Tesla'],
        ['code' => 'D34','description' => 'Texas'],
        ['code' => 'D35','description' => 'Caloría termoquímica'],
        ['code' => 'D37','description' => 'Caloría termoquímica por gramo Kelvin'],
        ['code' => 'D38','description' => 'Caloría termoquímica por segundo'],
        ['code' => 'D39','description' => 'Caloría termoquímica por segundo'],
        ['code' => 'D40','description' => 'Mil litros'],
        ['code' => 'D41','description' => 'Tonelada por metro cúbico'],
        ['code' => 'D42','description' => 'Año tropical'],
        ['code' => 'D43','description' => 'Unidad de masa atómica unificada'],
        ['code' => 'D44','description' => 'Var'],
        ['code' => 'D82','description' => 'Microvoltio'],
        ['code' => 'D83','description' => 'Metro de milinewton'],
        ['code' => 'D85','description' => 'Microvatios por metro cuadrado'],
        ['code' => 'D86','description' => 'Miliculombio'],
        ['code' => 'D87','description' => 'Milimole por kilogramo'],
        ['code' => 'D88','description' => 'Milicoulomb por metro cúbico'],
        ['code' => 'D89','description' => 'Milicoulomb por metro cuadrado'],
        ['code' => 'D9','description' => 'Dina por centímetro cuadrado'],
        ['code' => 'D90','description' => 'Metro cúbico (neto)'],
        ['code' => 'D91','description' => 'Movimiento rápido del ojo'],
        ['code' => 'D92','description' => 'Banda'],
        ['code' => 'D93','description' => 'Segundo por metro cúbico'],
        ['code' => 'D94','description' => 'Segundo por radianes metro cúbico'],
        ['code' => 'D95','description' => 'Joule por gramo'],
        ['code' => 'D96','description' => 'Libra bruta'],
        ['code' => 'D97','description' => 'Palet / unidad de carga'],
        ['code' => 'D98','description' => 'Libra masiva'],
        ['code' => 'D99','description' => 'Manga'],
        ['code' => 'DAA','description' => 'Decaer'],
        ['code' => 'DAD','description' => 'Diez dias'],
        ['code' => 'DAY','description' => 'Día'],
        ['code' => 'DB','description' => 'Libra seca'],
        ['code' => 'DC','description' => 'Disco (disco)'],
        ['code' => 'DD','description' => 'Grado'],
        ['code' => 'DE','description' => 'Trato'],
        ['code' => 'DEC','description' => 'Década'],
        ['code' => 'DG','description' => 'Decigramo'],
        ['code' => 'DI','description' => 'Dispensador'],
        ['code' => 'DJ','description' => 'Decagramo'],
        ['code' => 'DLT','description' => 'Decilitro'],
        ['code' => 'DMK','description' => 'Decímetro cuadrado'],
        ['code' => 'DMQ','description' => 'Decímetro cúbico'],
        ['code' => 'DMT','description' => 'Decímetro'],
        ['code' => 'DN','description' => 'Medidor de decinewton'],
        ['code' => 'DPC','description' => 'Docena de piezas'],
        ['code' => 'DPR','description' => 'Docena de pares'],
        ['code' => 'DPT','description' => 'Tonelaje de desplazamiento'],
        ['code' => 'DQ','description' => 'Registro de datos'],
        ['code' => 'DR','description' => 'Tambor'],
        ['code' => 'DRA','description' => 'Dram (EE. UU.)'],
        ['code' => 'DRI','description' => 'Dram (Reino Unido)'],
        ['code' => 'DRL','description' => 'Docena de rollos'],
        ['code' => 'DRM','description' => 'Drachm (Reino Unido)'],
        ['code' => 'GC','description' => 'Gramo por 100 gramos'],
        ['code' => 'GD','description' => 'Barril bruto'],
        ['code' => 'GE','description' => 'Libra por galón (EE. UU.)'],
        ['code' => 'GF','description' => 'Gramo por metro (gramo por 100'],
        ['code' => 'GFI','description' => 'Gramo de isótopo fisible'],
        ['code' => 'GGR','description' => 'Gran bruto'],
        ['code' => 'GH','description' => 'Medio galón (EE. UU.)'],
        ['code' => 'GIA','description' => 'Branquias (EE. UU.)'],
        ['code' => 'GII','description' => 'Gill (Reino Unido)'],
        ['code' => 'GJ','description' => 'Gramo por mililitro'],
        ['code' => 'GK','description' => 'Gramo por kilogramo'],
        ['code' => 'GL','description' => 'Gramo por litro'],
        ['code' => 'GLD','description' => 'Galón seco (EE. UU.)'],
        ['code' => 'GLI','description' => 'Galón (Reino Unido)'],
        ['code' => 'GLL','description' => 'Galón (EE. UU.)'],
        ['code' => 'GM','description' => 'Gramo por metro cuadrado'],
        ['code' => 'GN','description' => 'Galón bruto'],
        ['code' => 'GO','description' => 'Miligramos por metro cuadrado'],
        ['code' => 'GP','description' => 'Miligramo por metro cúbico'],
        ['code' => 'GQ','description' => 'Microgramo por metro cúbico'],
        ['code' => 'GRM','description' => 'Gramo'],
        ['code' => 'GRN','description' => 'Grano'],
        ['code' => 'GRO','description' => 'Bruto'],
        ['code' => 'GRT','description' => 'Tonelada de registro bruto'],
        ['code' => 'GT','description' => 'Tonelada bruta'],
        ['code' => 'GV','description' => 'Gigajoule'],
        ['code' => 'GW','description' => 'Galones por mil pies cúbicos'],
        ['code' => 'GWH','description' => 'Gigavatio hora'],
        ['code' => 'GY','description' => 'Yarda bruta'],
        ['code' => 'GZ','description' => 'Sistema de calibre'],
        ['code' => 'H1','description' => 'Media página - electrónico'],
        ['code' => 'H2','description' => 'Medio litro'],
        ['code' => 'HA','description' => 'Madeja'],
        ['code' => 'HAR','description' => 'Hectárea'],
        ['code' => 'HBA','description' => 'Hectobar'],
        ['code' => 'HBX','description' => 'Cien boxe'],
        ['code' => 'HC','description' => 'Cuenta de cien'],
        ['code' => 'HD','description' => 'Media docena'],
        ['code' => 'HE','description' => 'Centésimo de quilate'],
        ['code' => 'HF','description' => 'Cien pies'],
        ['code' => 'HGM','description' => 'Hectogramo'],
        ['code' => 'HH','description' => 'Cien pies cúbicos'],
        ['code' => 'K3','description' => 'Kilovoltio amperio hora reactiva'],
        ['code' => 'K5','description' => 'Kilovoltio amperio (reactivo)'],
        ['code' => 'K6','description' => 'Kilolitro'],
        ['code' => 'KA','description' => 'Pastel'],
        ['code' => 'KB','description' => 'Kilocarácter'],
        ['code' => 'KBA','description' => 'Kilobar'],
        ['code' => 'KD','description' => 'Kilogramo decimal'],
        ['code' => 'KEL','description' => 'Kelvin'],
        ['code' => 'KF','description' => 'Kilopaquete'],
        ['code' => 'KG','description' => 'Barrilete'],
        ['code' => 'KGM','description' => 'Kilogramo'],
        ['code' => 'KGS','description' => 'Kilogramo por segundo'],
        ['code' => 'KHZ','description' => 'Kilohercio'],
        ['code' => 'KI','description' => 'Kilogramo por milímetro de ancho'],
        ['code' => 'KJ','description' => 'Kilosegmento'],
        ['code' => 'KJO','description' => 'Kilojoule'],
        ['code' => 'KL','description' => 'Kilogramo por metro'],
        ['code' => 'KMH','description' => 'Kilómetro por hora'],
        ['code' => 'KMK','description' => 'Kilometro cuadrado'],
        ['code' => 'KMQ','description' => 'Kilogramo por metro cúbico'],
        ['code' => 'KNI','description' => 'Kilogramo de nitrógeno'],
        ['code' => 'KNS','description' => 'Kilogramo de sustancia nombrada'],
        ['code' => 'KNT','description' => 'Nudo'],
        ['code' => 'KO','description' => 'Miliequivalencia de potasa cáustica por gramo'],
        ['code' => 'KPA','description' => 'Kilopascal'],
        ['code' => 'KPH','description' => 'Kilogramo de hidróxido de potasio (cáustico'],
        ['code' => 'KPO','description' => 'Kilogramo de óxido de potasio'],
        ['code' => 'KPP','description' => 'Kilogramo de pentóxido de fósforo'],
        ['code' => 'KR','description' => 'KilorÃ¶ntgen'],
        ['code' => 'KS','description' => 'Mil libras por pulgada cuadrada'],
        ['code' => 'KSD','description' => 'Kilogramo de sustancia 90% seca'],
        ['code' => 'KSH','description' => 'Kilogramo de hidróxido de sodio (cáustico'],
        ['code' => 'KT','description' => 'Equipo'],
        ['code' => 'KTM','description' => 'Kilómetro'],
        ['code' => 'KTN','description' => 'Kilotonelada'],
        ['code' => 'KUR','description' => 'Kilogramo de uranio'],
        ['code' => 'KVA','description' => 'Kilovoltio - amperio'],
        ['code' => 'KVR','description' => 'Kilovar'],
        ['code' => 'KVT','description' => 'Kilovoltio'],
        ['code' => 'MC','description' => 'Microgramo'],
        ['code' => 'MCU','description' => 'Milicurie'],
        ['code' => 'MD','description' => 'Tonelada métrica seca al aire'],
        ['code' => 'MF','description' => 'Miligramo por pie cuadrado por lado'],
        ['code' => 'MGM','description' => 'Miligramo'],
        ['code' => 'MHZ','description' => 'Megahercio'],
        ['code' => 'MIK','description' => 'Milla cuadrada'],
        ['code' => 'MIL','description' => 'Mil'],
        ['code' => 'MIN','description' => 'Minuto'],
        ['code' => 'MIO','description' => 'Millón'],
        ['code' => 'MIU','description' => 'Millones de unidades internacionales'],
        ['code' => 'MK','description' => 'Miligramo por pulgada cuadrada'],
        ['code' => 'MLD','description' => 'Mil millones'],
        ['code' => 'MLT','description' => 'Mililitro'],
        ['code' => 'MMK','description' => 'Milímetro cuadrado'],
        ['code' => 'MMQ','description' => 'Milímetro cúbico'],
        ['code' => 'MMT','description' => 'Milímetro'],
        ['code' => 'MON','description' => 'Mes'],
        ['code' => 'MPA','description' => 'Megapascal'],
        ['code' => 'MQ','description' => 'Mil metros'],
        ['code' => 'MQH','description' => 'Metro cúbico por hora'],
        ['code' => 'MQS','description' => 'Metro cúbico por segundo'],
        ['code' => 'MSK','description' => 'Metro por segundo al cuadrado'],
        ['code' => 'MT','description' => 'Estera'],
        ['code' => 'MTK','description' => 'Metro cuadrado'],
        ['code' => 'MTQ','description' => 'Metro cúbico'],
        ['code' => 'MTR','description' => 'Metro'],
        ['code' => 'MTS','description' => 'Metro por segundo'],
        ['code' => 'MV','description' => 'Número de mults'],
        ['code' => 'MVA','description' => 'Megavoltio - amperio'],
        ['code' => 'MWH','description' => 'Megavatio hora (1000 kW.h)'],
        ['code' => 'N1','description' => 'Caloría de la pluma'],
        ['code' => 'N2','description' => 'Número de líneas'],
        ['code' => 'N3','description' => 'Punto de impresión'],
        ['code' => 'NA','description' => 'Miligramo por kilogramo'],
        ['code' => 'NAR','description' => 'Número de artículos'],
        ['code' => 'NB','description' => 'Barcaza'],
        ['code' => 'NBB','description' => 'Número de bobinas'],
        ['code' => 'NC','description' => 'Coche'],
        ['code' => 'NCL','description' => 'Número de celdas'],
        ['code' => 'ND','description' => 'Barril neto'],
        ['code' => 'NE','description' => 'Litro neto'],
        ['code' => 'NEW','description' => 'Newton'],
        ['code' => 'PB','description' => 'Par de pulgadas'],
        ['code' => 'PD','description' => 'Almohadilla'],
        ['code' => 'PE','description' => 'Libra equivalente'],
        ['code' => 'PF','description' => 'Palet (elevador)'],
        ['code' => 'PG','description' => 'Lámina'],
        ['code' => 'PGL','description' => 'Galón de prueba'],
        ['code' => 'PI','description' => 'Tono PI'],
        ['code' => 'PK','description' => 'Paquete PK'],
        ['code' => 'PL','description' => 'Cubo'],
        ['code' => 'PM','description' => 'Porcentaje de libra'],
        ['code' => 'PN','description' => 'Libra neta'],
        ['code' => 'PO','description' => 'Libra por pulgada de longitud'],
        ['code' => 'PQ','description' => 'Página por pulgada'],
        ['code' => 'PR','description' => 'Par'],
        ['code' => 'PS','description' => 'Libra fuerza por pulgada cuadrada'],
        ['code' => 'PT','description' => 'Pinta (EE. UU.)'],
        ['code' => 'PTD','description' => 'Pinta seca (EE. UU.)'],
        ['code' => 'PTI','description' => 'Pinta (Reino Unido)'],
        ['code' => 'PTL','description' => 'Pinta líquida (EE. UU.)'],
        ['code' => 'PU','description' => 'Bandeja / paquete de bandeja'],
        ['code' => 'PV','description' => 'Media pinta (EE. UU.)'],
        ['code' => 'PW','description' => 'Libra por pulgada de ancho'],
        ['code' => 'PY','description' => 'Picotear seco (EE. UU.)'],
        ['code' => 'PZ','description' => 'Picotear seco (Reino Unido)'],
        ['code' => 'Q3','description' => 'Comida'],
        ['code' => 'QA','description' => 'Página - facsímil'],
        ['code' => 'QAN','description' => 'Trimestre (de un año)'],
        ['code' => 'QB','description' => 'Página - copia impresa'],
        ['code' => 'QD','description' => 'Cuarto de docena'],
        ['code' => 'QH','description' => 'Un cuarto de hora'],
        ['code' => 'QK','description' => 'Cuarto de kilogramo'],
        ['code' => 'QR','description' => 'Mano de papel'],
        ['code' => 'QT','description' => 'Cuarto de galón (EE. UU.)'],
        ['code' => 'QTD','description' => 'Cuarto seco (EE. UU.)'],
        ['code' => 'QTI','description' => 'Cuarto (Reino Unido)'],
        ['code' => 'QTL','description' => 'Cuarto líquido (EE. UU.)'],
        ['code' => 'QTR','description' => 'Trimestre (Reino Unido)'],
        ['code' => 'R1','description' => 'Pica'],
        ['code' => 'R4','description' => 'Caloría'],
        ['code' => 'R9','description' => 'Mil metros cúbicos'],
        ['code' => 'RA','description' => 'Estante'],
        ['code' => 'RD','description' => 'Varilla'],
        ['code' => 'RG','description' => 'Anillo'],
        ['code' => 'SW','description' => 'Madeja'],
        ['code' => 'SX','description' => 'Envío'],
        ['code' => 'T0','description' => 'Línea de telecomunicaciones en servicio'],
        ['code' => 'T1','description' => 'Miles de libras brutos'],
        ['code' => 'T3','description' => 'Mil piezas'],
        ['code' => 'T4','description' => 'Mil bolsas'],
        ['code' => 'T5','description' => 'Mil carcasas'],
        ['code' => 'T6','description' => 'Mil galones (EE. UU.)'],
        ['code' => 'T7','description' => 'Mil impresiones'],
        ['code' => 'T8','description' => 'Mil pulgadas lineales'],
        ['code' => 'TA','description' => 'Décimo pie cúbico'],
        ['code' => 'TAH','description' => 'Kiloamperio hora (mil amperios hora)'],
        ['code' => 'TC','description' => 'Camión de carga'],
        ['code' => 'TD','description' => 'Termia'],
        ['code' => 'TE','description' => 'Totalizador'],
        ['code' => 'TF','description' => 'Diez yardas cuadradas'],
        ['code' => 'TI','description' => 'Mil pulgadas cuadradas'],
        ['code' => 'TJ','description' => 'Mil centímetros cuadrados'],
        ['code' => 'TK','description' => 'Tanque, rectangular'],
        ['code' => 'TL','description' => 'Mil pies (lineal)'],
        ['code' => 'TN','description' => 'Estaño'],
        ['code' => 'TNE','description' => 'Tonelada (tonelada métrica)'],
        ['code' => 'TP','description' => 'Paquete de diez'],
        ['code' => 'TPR','description' => 'Diez pares'],
        ['code' => 'TQ','description' => 'Mil pies'],
        ['code' => 'TQD','description' => 'Mil metros cúbicos por día'],
        ['code' => 'TR','description' => 'Diez pies cuadrados'],
        ['code' => 'TRL','description' => 'Billón (EUR)'],
        ['code' => 'TS','description' => 'Mil pies cuadrados'],
        ['code' => 'TSD','description' => 'Tonelada de sustancia 90% seca'],
        ['code' => 'TSH','description' => 'Tonelada de vapor por hora'],
        ['code' => 'TT','description' => 'Mil metros lineales'],
        ['code' => 'TU','description' => 'Tubo'],
        ['code' => 'TV','description' => 'Mil kilogramos'],
        ['code' => 'TW','description' => 'Mil hojas'],
        ['code' => 'TY','description' => 'Tanque, cilíndrico'],
        ['code' => 'U1','description' => 'Tratamiento'],
        ['code' => 'U2','description' => 'Tableta'],
        ['code' => 'UA','description' => 'Torr'],
        ['code' => 'UB','description' => 'Línea de telecomunicaciones en servicio'],
        ['code' => 'UC','description' => 'Puerto de telecomunicaciones'],
        ['code' => 'UD','description' => 'Décimo minuto'],
        ['code' => 'WI','description' => 'Peso por pulgada cuadrada'],
        ['code' => 'WM','description' => 'Mes de trabajo'],
        ['code' => 'WR','description' => 'Envoltura'],
        ['code' => 'WSD','description' => 'Estándar'],
        ['code' => 'WTT','description' => 'Vatio'],
        ['code' => 'WW','description' => 'Mililitro de agua'],
        ['code' => 'X1','description' => 'Cadena'],
        ['code' => 'YDK','description' => 'Yarda cuadrada'],
        ['code' => 'YDQ','description' => 'Yarda cúbica'],
        ['code' => 'YL','description' => 'Cien yardas lineales'],
        ['code' => 'YRD','description' => 'Yarda'],
        ['code' => 'YT','description' => 'Diez yardas'],
        ['code' => 'Z1','description' => 'Camioneta elevadora'],
        ['code' => 'Z2','description' => 'Cofre'],
        ['code' => 'Z3','description' => 'Barril'],
        ['code' => 'Z4','description' => 'Pipa'],
        ['code' => 'Z5','description' => 'Arrastrar'],
        ['code' => 'Z6','description' => 'Punto de conferencia'],
        ['code' => 'Z8','description' => 'Pagina de noticias'],
        ['code' => 'ZP','description' => 'Pagina']
    ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('unit_measure');
    }
}
